name: Deploy to web server
on:
  push:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v2
     - run: pip install -r requirements.txt
     - run: python test_api.py
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test_pull_request
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      if: github.ref == 'refs/heads/main'
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/api
          git pull origin main
          git status
          systemctl restart apiDemo