name: Python Test

on: 
  push:
    branch: [dev]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v2
     - run: pip install -r requirements.txt
     - run: python test_api.py